// apps/ng-cocokits/src/app/header/header.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { IconButtonComponent , SvgIconComponent , FormFieldComponent ,
  InputComponent,
  PrefixComponent,
  SuffixComponent,
  } from '@cocokits/angular-components';
import { Icons } from "@cocokits/common-icons";

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [CommonModule , IconButtonComponent , SvgIconComponent ,   FormFieldComponent,
    InputComponent,
    PrefixComponent,
    SuffixComponent,
    SvgIconComponent, ],
  templateUrl: './header.component.html',
  styleUrl: './header.component.scss',
})
export class HeaderComponent {
  protected readonly Icons = Icons;
}

<nav class='header'>
  <!-- menu   -->
  <div class='menu'>
    <button cck-icon-button type="default" size="md" type="secondary">
      <cck-svg-icon [icon]="Icons.dollar"></cck-svg-icon>
    </button>
    <button class='menu_icon' cck-icon-button type="default" size="md" type="secondary">
      <cck-svg-icon [icon]="Icons.info"></cck-svg-icon>
    </button>
    <ul class='nav_links'>
      <li>
        <a href="#">
          Home
          <cck-svg-icon [icon]="Icons.arrowHeadDown" size="lg"></cck-svg-icon>
        </a>
      </li>
      <li>
        <a href="#">
          Products
          <cck-svg-icon [icon]="Icons.arrowHeadDown" size="lg"></cck-svg-icon>
        </a>
      </li>
      <li>
        <a href="#">
          Pricing
          <cck-svg-icon [icon]="Icons.arrowHeadDown" size="lg"></cck-svg-icon>
        </a>
      </li>
      <li>
        <a href="#">
          Contact
          <cck-svg-icon [icon]="Icons.arrowHeadDown" size="lg"></cck-svg-icon>
        </a>
      </li>
    </ul>
  </div>
  <!-- search  -->
  <button cck-icon-button class='search_btn' type="secondary" size="md">
    <cck-svg-icon [icon]="Icons.search" />
  </button>
  <cck-form-field class='search' >
    <input cck-input placeholder="Search ..." />
    <cck-prefix>
      <cck-svg-icon [size]="'xl'" [icon]="Icons.search"></cck-svg-icon>
    </cck-prefix>
  </cck-form-field>
</nav>

// apps/react-cocokits/src/app/header/header.tsx
import styles from './header.module.scss';
import { Icons } from '@cocokits/common-icons';
import {
  SvgIcon,
  FormField,
  Input,
  IconButton,
  Prefix,
  Suffix,
} from '@cocokits/react-components';

export function Header() {
  return (
    <nav className={styles['header']}>
      {/* menu  */}
      <div className={styles['menu']}>
        <IconButton type="secondary" size="md" color="brand">
          <SvgIcon icon={Icons.dollar} />
        </IconButton>
        <IconButton
          className={styles['menu_icon']}
          type="secondary"
          size="md"
          color="brand"
        >
          <SvgIcon icon={Icons.info} />
        </IconButton>
        <ul className={styles['nav_links']}>
          <li>
            <a href="#">
              Home
              <SvgIcon size="lg" icon={Icons.arrowHeadDown} />
            </a>
          </li>
          <li>
            <a href="#">
              Products
              <SvgIcon size="lg" icon={Icons.arrowHeadDown} />
            </a>
          </li>
          <li>
            <a href="#">
              Pricing
              <SvgIcon size="lg" icon={Icons.arrowHeadDown} />
            </a>
          </li>
          <li>
            <a href="#">
              Contact
              <SvgIcon size="lg" icon={Icons.arrowHeadDown} />
            </a>
          </li>
        </ul>
      </div>
      {/* search */}
      <IconButton
        className={styles['search_btn']}
        type="secondary"
        size="md"
        color="brand"
      >
        <SvgIcon icon={Icons.search} />
      </IconButton>
      <FormField className={styles['search']}>
        <Input  placeholder="Search ..." />
        <Prefix>
          <SvgIcon
            size="xl"
            icon={Icons.search}
          ></SvgIcon>
        </Prefix>
      </FormField>
    </nav>
  );
}

export default Header;
