// apps/react-cocokits/src/app/app.tsx
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { Button, Checkbox, Option, FormField, Input, Label, removeAmountFormat, Select, ThemeConfigContext, toAmountFormat, Trailing } from '@cocokits/react-components';
import styles from './app.module.scss';

import { framesXThemeConfig } from '@cocokits/theme-frames-x';
import { useState } from 'react';

export function App() {
  const [value, setValue] = useState("");
  
  return (
    <ThemeConfigContext.Provider value={framesXThemeConfig}>
      <div className='app-host'>
        <Button>Hello</Button>
        <Checkbox>This is a checkbox</Checkbox>

        <FormField>
          <Label>Select amount</Label>
          <Input
            value={value}
            onFocus={() => setValue(removeAmountFormat(value))}
            onBlur={() => setValue(toAmountFormat(value))}
            onChange={(e) => setValue(e.target.value)}
          />
          <Trailing>
            <Select value="USD">
              <Option value="USD">USD</Option>
              <Option value="EUR">EUR</Option>
              <Option value="JPY">JPY</Option>
              <Option value="CNY">CNY</Option>
              <Option value="KRW">KRW</Option>
            </Select>
          </Trailing>
        </FormField>
      </div>
    </ThemeConfigContext.Provider>
  );
}

export default App;

// apps/ng-cocokits/src/app/app.component.ts
import { Component, signal } from '@angular/core';
import { RouterModule } from '@angular/router';

import { ButtonComponent, CheckboxComponent, FormFieldComponent, InputComponent, LabelComponent, OptionComponent, removeAmountFormat, SelectComponent, toAmountFormat, TrailingComponent } from '@cocokits/angular-components';

@Component({
  standalone: true,
  imports: [
    RouterModule,
    ButtonComponent,
    CheckboxComponent,
    FormFieldComponent,
    InputComponent,
    LabelComponent,
    OptionComponent,
    SelectComponent,
    TrailingComponent,
  ],
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
})
export class AppComponent {
  title = 'ng-cocokits';

  protected value = signal("");

  protected onChange(event: Event) {
    this.value.set((event.currentTarget as HTMLInputElement).value);
  }

  protected onFocus() {
    this.value.set(removeAmountFormat(this.value()));
  }

  protected onBlur() {
    this.value.set(toAmountFormat(this.value()));
  }
}

<button cck-button>Button</button>
<cck-checkbox>This is a Checkbox</cck-checkbox>



<cck-form-field>
  <cck-label>Select amount</cck-label>
  <input
    cck-input
    (change)="onChange($event)"
    (focus)="onFocus()"
    (blur)="onBlur()"
    [value]="value()"
  />
  <cck-trailing>
    <cck-select value="USD" appendTo="body">
      <cck-option value="USD">USD</cck-option>
      <cck-option value="EUR">EUR</cck-option>
      <cck-option value="JPY">JPY</cck-option>
      <cck-option value="CNY">CNY</cck-option>
      <cck-option value="KRW">KRW</cck-option>
    </cck-select>
  </cck-trailing>
</cck-form-field>


<router-outlet></router-outlet>
